name: tensorflow_wasm
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  # path: ^1.8.0
  wasm:
  universal_html:
  wasm_interop:
  http:
  logging: ^1.0.2
  collection:
  json_annotation:
  path:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner:
  json_serializable:
